# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--clib
#
set( CLIB
src/uuid4/src/uuid4.c
src/uuid4/src/uuid4.h
)

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleObjCUUIDFoundation.m
src/NSUUID.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/generic/MulleObjCLoader+MulleObjCUUIDFoundation.m
)
